window.CARDS = {
    monsters: [
        { id: "mon1", name: "Harpy Lady Sisters", cost: 1, copies: 1, type: "effect" },
        { id: "mon2", name: "Nimble Momonga", cost: 1, copies: 4, type: "effect" },
        { id: "mon3", name: "Nimble Musasabi", cost: 1, copies: 3, type: "effect" },
        { id: "mon4", name: "Wall Shadow", cost: 1, copies: 1, type: "effect" },
        { id: "mon5", name: "Z-Metal Tank", cost: 1, copies: 1, type: "effect" },
        { id: "mon6", name: "Y-Dragon Head", cost: 1, copies: 1, type: "effect" },
        { id: "mon7", name: "Spirit of The Pot of Greed", cost: 1, copies: 1, type: "effect" },
        { id: "mon8", name: "Red-Eyes Black Metal Dragon", cost: 1, copies: 1, type: "effect" },
        { id: "mon9", name: "Drill Bug", cost: 1, copies: 1, type: "effect" },
        { id: "mon10", name: "The Trojan Horse", cost: 1, copies: 2, type: "effect" },
        { id: "mon11", name: "Larvae Moth", cost: 1, copies: 1, type: "effect" },
        { id: "mon12", name: "Cocoon of Evolution", cost: 1, copies: 1, type: "effect" },
        { id: "mon13", name: "Great Moth", cost: 1, copies: 1, type: "effect" },
        { id: "mon14", name: "Chaos Necromancer", cost: 1, copies: 1, type: "effect" },
        { id: "mon15", name: "Regenerating Mummy", cost: 1, copies: 1, type: "effect" },
        { id: "mon16", name: "Strike Ninja", cost: 1, copies: 1, type: "effect" },
        { id: "mon17", name: "Lekunga", cost: 1, copies: 1, type: "effect" },
        { id: "mon18", name: "Old Vindictive Magician", cost: 1, copies: 1, type: "effect" },
        { id: "mon19", name: "Alpha The Magnet Warrior", cost: 1, copies: 1, type: "normal" },
        { id: "mon20", name: "Gamma The Magnet Warrior", cost: 1, copies: 1, type: "normal" },
        { id: "mon21", name: "Jack's Knight", cost: 1, copies: 1, type: "normal" },
        { id: "mon22", name: "Queen's Knight", cost: 1, copies: 1, type: "normal" },
        { id: "mon23", name: "Beta The Magnet Warrior", cost: 3, copies: 1, type: "normal" },
        { id: "mon24", name: "X-Head Cannon", cost: 3, copies: 1, type: "normal" },
        { id: "mon25", name: "King's Knight", cost: 3, copies: 1, type: "effect" },
        { id: "mon26", name: "Drillago", cost: 3, copies: 1, type: "effect" },
        { id: "mon27", name: "Iron Blacksmith Kotetsu", cost: 3, copies: 1, type: "effect" },
        { id: "mon28", name: "Blizzard Dragon", cost: 3, copies: 1, type: "effect" },
        { id: "mon29", name: "Gilasaurus", cost: 3, copies: 2, type: "effect" },
        { id: "mon30", name: "Insect Princess", cost: 3, copies: 1, type: "effect" },
        { id: "mon31", name: "Mythical Beast of Serket", cost: 3, copies: 1, type: "effect" },
        { id: "mon32", name: "Toon Summoned Skull", cost: 3, copies: 1, type: "effect" },
        { id: "mon33", name: "Berfomet", cost: 3, copies: 1, type: "effect" },
        { id: "mon34", name: "Divine Knight Ishzark", cost: 3, copies: 1, type: "effect" },
        { id: "mon35", name: "Lesser Fiend", cost: 3, copies: 1, type: "effect" },
        { id: "mon36", name: "Cyber Dragon", cost: 3, copies: 3, type: "effect" },
        { id: "mon37", name: "Blue Flame Swordsman", cost: 3, copies: 1, type: "effect" },
        { id: "mon38", name: "Don Zaloog", cost: 3, copies: 1, type: "effect" },
        { id: "mon39", name: "Summoned Skull", cost: 3, copies: 1, type: "normal" },
        { id: "mon40", name: "The Tricky", cost: 3, copies: 2, type: "effect" },
        { id: "mon41", name: "Guardian Sphinx", cost: 3, copies: 1, type: "effect" },
        { id: "mon42", name: "Thestalos The Firestorm Monarch", cost: 3, copies: 1, type: "effect" },
        { id: "mon43", name: "Freed The Matchless General", cost: 3, copies: 1, type: "effect" },
        { id: "mon44", name: "Archfiend of Gilfer", cost: 3, copies: 1, type: "effect" },
        { id: "mon45", name: "Vorse Raider", cost: 3, copies: 1, type: "normal" },
        { id: "mon46", name: "Slate Warrior", cost: 3, copies: 1, type: "effect" },
        { id: "mon47", name: "Sealed Dark Magician", cost: 3, copies: 1, type: "effect" },
        { id: "mon48", name: "Goblin Attack Force", cost: 3, copies: 2, type: "effect" },
        { id: "mon49", name: "Goblin Elite Attack Force", cost: 3, copies: 1, type: "effect" },
        { id: "mon50", name: "Time Wizard", cost: 3, copies: 1, type: "effect" },
        { id: "mon51", name: "Blast Sphere", cost: 3, copies: 1, type: "effect" },
        { id: "mon52", name: "Viser Des", cost: 3, copies: 1, type: "effect" },
        { id: "mon53", name: "Gil Garth", cost: 3, copies: 1, type: "normal" },
        { id: "mon54", name: "Dunames Dark Witch", cost: 3, copies: 1, type: "normal" },
        { id: "mon55", name: "Marshmallon", cost: 3, copies: 2, type: "effect" },
        { id: "mon56", name: "Man-Eater Bug", cost: 3, copies: 2, type: "effect" },
        { id: "mon57", name: "Ritual Raven", cost: 3, copies: 2, type: "effect" },
        { id: "mon58", name: "Chron The Mage", cost: 3, copies: 2, type: "effect" },
        { id: "mon59", name: "Panther Warrior", cost: 3, copies: 1, type: "effect" },
        { id: "mon60", name: "Plague Wolf", cost: 3, copies: 1, type: "effect" },
        { id: "mon61", name: "Vortex Trooper", cost: 3, copies: 1, type: "effect" },
        { id: "mon62", name: "Rigorous Reaver", cost: 3, copies: 1, type: "effect" },
        { id: "mon63", name: "Makyura The Destructor", cost: 3, copies: 1, type: "effect" },
        { id: "mon64", name: "Diskblade Rider", cost: 3, copies: 2, type: "effect" },
        { id: "mon65", name: "Red-Eyes Wyvern", cost: 3, copies: 1, type: "effect" },
        { id: "mon66", name: "Blade Knight", cost: 3, copies: 1, type: "effect" },
        { id: "mon67", name: "Harpy Lady 3", cost: 3, copies: 1, type: "effect" },
        { id: "mon68", name: "Cross-Sword Beetle", cost: 3, copies: 1, type: "effect" },
        { id: "mon69", name: "The King of D.", cost: 3, copies: 1, type: "effect" },
        { id: "mon70", name: "Zombyra The Dark", cost: 3, copies: 1, type: "effect" },
        { id: "mon71", name: "Kycoo The Ghost Destroyer", cost: 3, copies: 1, type: "effect" },
        { id: "mon72", name: "Toon Gemini Elf", cost: 3, copies: 1, type: "effect" },
        { id: "mon73", name: "Self Destruct Ant", cost: 3, copies: 1, type: "effect" },
        { id: "mon74", name: "Blue-Eyes White Dragon", cost: 5, copies: 1, type: "normal" },
        { id: "mon75", name: "Manju of The Ten Thousand Hands", cost: 5, copies: 3, type: "effect" },
        { id: "mon76", name: "Morphing Jar", cost: 5, copies: 1, type: "effect" },
        { id: "mon77", name: "King of The Swamp", cost: 5, copies: 3, type: "effect" },
        { id: "mon78", name: "Granmarg The Rock Monarch", cost: 5, copies: 1, type: "effect" },
        { id: "mon79", name: "Jizzno", cost: 5, copies: 1, type: "effect" },
        { id: "mon80", name: "Machine King", cost: 5, copies: 1, type: "effect" },
        { id: "mon81", name: "The Fiend Megacyber", cost: 5, copies: 1, type: "effect" },
        { id: "mon82", name: "Satellite Cannon", cost: 5, copies: 1, type: "effect" },
        { id: "mon83", name: "Dark Magician Girl", cost: 5, copies: 1, type: "effect" },
        { id: "mon84", name: "Vampire Lord", cost: 5, copies: 1, type: "effect" },
        { id: "mon85", name: "Mobius The Frost Monarch", cost: 5, copies: 1, type: "effect" },
        { id: "mon86", name: "Gaia The Fierce Knight", cost: 5, copies: 1, type: "effect" },
        { id: "mon87", name: "Helpoemer", cost: 5, copies: 1, type: "effect" },
        { id: "mon88", name: "Insect Queen", cost: 5, copies: 1, type: "effect" },
        { id: "mon89", name: "Cyber Jar", cost: 5, copies: 1, type: "effect" },
        { id: "mon90", name: "Night Assailant", cost: 5, copies: 1, type: "effect" },
        { id: "mon91", name: "D. D. Warrior Lady", cost: 5, copies: 1, type: "effect" },
        { id: "mon92", name: "King Tiger Wanghu", cost: 5, copies: 1, type: "effect" },
        { id: "mon93", name: "Kaibaman", cost: 5, copies: 1, type: "effect" },
        { id: "mon94", name: "Reflect Bounder", cost: 5, copies: 1, type: "effect" },
        { id: "mon95", name: "Dark Ruler Ha Des", cost: 5, copies: 1, type: "effect" },
        { id: "mon96", name: "Blue-Eyes Toon Dragon", cost: 5, copies: 1, type: "effect" },
        { id: "mon97", name: "Valkyrion The Magna Warrior", cost: 5, copies: 1, type: "effect" },
        { id: "mon98", name: "Dark Magician of Chaos", cost: 10, copies: 1, type: "effect" },
        { id: "mon99", name: "Gorz The Emissary of Darkness", cost: 10, copies: 1, type: "effect" },
        { id: "mon100", name: "Light and Darkness Dragon", cost: 10, copies: 1, type: "effect" },
        { id: "mon101", name: "Hino-Kagu-Tsuchi", cost: 10, copies: 1, type: "effect" },
        { id: "mon102", name: "Lava Golem", cost: 10, copies: 1, type: "effect" },
        { id: "mon103", name: "Dark Necrofear", cost: 10, copies: 1, type: "effect" },
        { id: "mon104", name: "Tyrant Dragon", cost: 10, copies: 1, type: "effect" },
        { id: "mon105", name: "Black Luster Soldier - Envoy of the Beginning", cost: 10, copies: 1, type: "effect" },
        { id: "mon106", name: "Yamata Dragon", cost: 10, copies: 1, type: "effect" },
        { id: "mon107", name: "Buster Blader", cost: 10, copies: 1, type: "effect" },
        { id: "mon108", name: "Barrel Dragon", cost: 10, copies: 1, type: "effect" },
        { id: "mon109", name: "Red-Eyes Zombie Dragon", cost: 5, copies: 1, type: "effect" },
        { id: "mon110", name: "Simorgh, Bird of Ancestry", cost: 5, copies: 1, type: "effect" },
        { id: "mon111", name: "Chaos Emperor Dragon - Envoy of The End", cost: 20, copies: 1, type: "effect" }
    ],

    spells: [
        { id: "sp1", name: "Yami", cost: 1, copies: 1, type: "spell" },
        { id: "sp2", name: "Mountain", cost: 1, copies: 1, type: "spell" },
        { id: "sp3", name: "Wasteland", cost: 1, copies: 1, type: "spell" },
        { id: "sp4", name: "Sogen", cost: 1, copies: 1, type: "spell" },
        { id: "sp5", name: "Forest", cost: 1, copies: 1, type: "spell" },
        { id: "sp6", name: "Umi", cost: 1, copies: 1, type: "spell" },
        { id: "sp7", name: "Ayers Rock Sunrise", cost: 1, copies: 2, type: "spell" },
        { id: "sp8", name: "Polymerization", cost: 1, copies: 6, type: "spell" },
        { id: "sp9", name: "Re-Fusion", cost: 1, copies: 1, type: "spell" },
        { id: "sp10", name: "De-Fusion", cost: 1, copies: 1, type: "spell" },
        { id: "sp11", name: "Dark Dragon Ritual", cost: 1, copies: 1, type: "spell" },
        { id: "sp12", name: "Black Magic Ritual", cost: 1, copies: 1, type: "spell" },
        { id: "sp13", name: "Black Luster Ritual", cost: 1, copies: 1, type: "spell" },
        { id: "sp14", name: "Contract With The Dark Master", cost: 1, copies: 1, type: "spell" },
        { id: "sp15", name: "White Dragon Ritual", cost: 1, copies: 1, type: "spell" },
        { id: "sp16", name: "Black Illusion Ritual", cost: 1, copies: 1, type: "spell" },
        { id: "sp17", name: "Hamburger Recipe", cost: 1, copies: 1, type: "spell" },
        { id: "sp18", name: "Commencement Dance", cost: 1, copies: 1, type: "spell" },
        { id: "sp19", name: "Curse of The Masked Beast", cost: 1, copies: 1, type: "spell" },
        { id: "sp20", name: "Turtle Oath", cost: 1, copies: 1, type: "spell" },
        { id: "sp21", name: "Magical Labyrinth", cost: 1, copies: 1, type: "spell" },
        { id: "sp22", name: "Fulfillment of The Contract", cost: 1, copies: 2, type: "spell" },
        { id: "sp23", name: "Ritual Weapon", cost: 1, copies: 3, type: "spell" },
        { id: "sp24", name: "Fusion Weapon", cost: 1, copies: 3, type: "spell" },
        { id: "sp25", name: "Jam Breeding Machine", cost: 1, copies: 1, type: "spell" },
        { id: "sp26", name: "Burning Land", cost: 1, copies: 1, type: "spell" },
        { id: "sp27", name: "Infinite Cards", cost: 1, copies: 1, type: "spell" },
        { id: "sp28", name: "Fuma Shuriken", cost: 1, copies: 1, type: "spell" },
        { id: "sp29", name: "Salamandra", cost: 1, copies: 2, type: "spell" },
        { id: "sp30", name: "Lightning Blade", cost: 1, copies: 1, type: "spell" },
        { id: "sp31", name: "Fusion Sword Murasame Blade", cost: 1, copies: 1, type: "spell" },
        { id: "sp32", name: "7 Completed", cost: 1, copies: 1, type: "spell" },
        { id: "sp33", name: "Spirit Message 'I'", cost: 1, copies: 2, type: "spell" },
        { id: "sp34", name: "Spirit Message 'N'", cost: 1, copies: 2, type: "spell" },
        { id: "sp35", name: "Spirit Message 'A'", cost: 1, copies: 2, type: "spell" },
        { id: "sp36", name: "Spirit Message 'L'", cost: 1, copies: 2, type: "spell" },
        { id: "sp37", name: "Insect Barrier", cost: 1, copies: 1, type: "spell" },
        { id: "sp38", name: "Magical Dimension", cost: 1, copies: 1, type: "spell" },
        { id: "sp39", name: "Roulette Spider", cost: 1, copies: 1, type: "spell" },
        { id: "sp40", name: "Tricky Spell 4", cost: 1, copies: 1, type: "spell" },
        { id: "sp41", name: "Multiply", cost: 1, copies: 1, type: "spell" },
        { id: "sp42", name: "Detonate", cost: 1, copies: 1, type: "spell" },
        { id: "sp43", name: "Dark Room of Nightmare", cost: 1, copies: 1, type: "spell" },
        { id: "sp44", name: "Marshmallon Glasses", cost: 1, copies: 1, type: "spell" },
        { id: "sp45", name: "Toon World", cost: 1, copies: 2, type: "spell" },
        { id: "sp46", name: "Multiplication of Ants", cost: 1, copies: 1, type: "spell" },
        { id: "sp47", name: "Book of Taiyou", cost: 1, copies: 2, type: "spell" },
        { id: "sp48", name: "Restructer Revolution", cost: 1, copies: 1, type: "spell" },
        { id: "sp49", name: "Inferno Fire Blast", cost: 1, copies: 1, type: "spell" },
        { id: "sp50", name: "Tremendous Fire", cost: 1, copies: 1, type: "spell" },
        { id: "sp51", name: "Hinotama", cost: 1, copies: 3, type: "spell" },
        { id: "sp52", name: "Elegant Egotist", cost: 1, copies: 1, type: "spell" },
        { id: "sp53", name: "The Warrior Returning Alive", cost: 1, copies: 2, type: "spell" },
        { id: "sp54", name: "Creature Swap", cost: 1, copies: 2, type: "spell" },

        { id: "sp55", name: "Card of Safe Return", cost: 3, copies: 1, type: "spell" },
        { id: "sp56", name: "Chorus of Sanctuary", cost: 3, copies: 1, type: "spell" },
        { id: "sp57", name: "Ribbon of Rebirth", cost: 3, copies: 2, type: "spell" },
        { id: "sp58", name: "Malevolent Nuzzler", cost: 3, copies: 2, type: "spell" },
        { id: "sp59", name: "A Legendary Ocean", cost: 3, copies: 2, type: "spell" },
        { id: "sp60", name: "Dark Sanctuary", cost: 3, copies: 1, type: "spell" },
        { id: "sp61", name: "Mystical Space Typhoon", cost: 3, copies: 2, type: "spell" },
        { id: "sp62", name: "Enemy Controller", cost: 3, copies: 1, type: "spell" },
        { id: "sp63", name: "Dedication Through Light and Darkness", cost: 3, copies: 1, type: "spell" },
        { id: "sp64", name: "Book of Moon", cost: 3, copies: 1, type: "spell" },
        { id: "sp65", name: "The Flute of Summoning Kuriboh", cost: 3, copies: 1, type: "spell" },
        { id: "sp66", name: "Card Trader", cost: 3, copies: 1, type: "spell" },
        { id: "sp67", name: "Ground Collapse", cost: 3, copies: 3, type: "spell" },
        { id: "sp68", name: "Silent Doom", cost: 3, copies: 1, type: "spell" },
        { id: "sp69", name: "Emblem of Dragon Destroyer", cost: 3, copies: 1, type: "spell" },
        { id: "sp70", name: "Preparation of Rites", cost: 3, copies: 1, type: "spell" },
        { id: "sp71", name: "Swing of Memories", cost: 3, copies: 1, type: "spell" },
        { id: "sp72", name: "Fiend's Sanctuary", cost: 3, copies: 1, type: "spell" },
        { id: "sp73", name: "Stray Lambs", cost: 3, copies: 1, type: "spell" },
        { id: "sp74", name: "Scapegoat", cost: 3, copies: 2, type: "spell" },
        { id: "sp75", name: "Dragon's Gunfire", cost: 3, copies: 1, type: "spell" },
        { id: "sp76", name: "Stamping Destruction", cost: 3, copies: 2, type: "spell" },
        { id: "sp77", name: "Brain Control", cost: 3, copies: 1, type: "spell" },
        { id: "sp78", name: "Fissure", cost: 3, copies: 2, type: "spell" },
        { id: "sp79", name: "Tribute to The Doomed", cost: 3, copies: 1, type: "spell" },
        { id: "sp80", name: "Shield Crush", cost: 3, copies: 2, type: "spell" },
        { id: "sp81", name: "Dark Magic Attack", cost: 3, copies: 1, type: "spell" },
        { id: "sp82", name: "Foolish Burial", cost: 3, copies: 2, type: "spell" },
        { id: "sp83", name: "Fusion Sage", cost: 3, copies: 2, type: "spell" },
        { id: "sp84", name: "Terraforming", cost: 3, copies: 2, type: "spell" },
        { id: "sp85", name: "The Flute of Summoning Dragon", cost: 3, copies: 2, type: "spell" },
        { id: "sp86", name: "Union Attack", cost: 3, copies: 1, type: "spell" },
        { id: "sp87", name: "A Wingbeat of Giant Dragon", cost: 3, copies: 1, type: "spell" },
        { id: "sp88", name: "Thousand Knives", cost: 3, copies: 1, type: "spell" },
        { id: "sp89", name: "Magical Stone Excavation", cost: 3, copies: 1, type: "spell" },
        { id: "sp90", name: "Spell Reproduction", cost: 3, copies: 1, type: "spell" },
        { id: "sp91", name: "The Shallow Grave", cost: 3, copies: 1, type: "spell" },
        { id: "sp92", name: "Swords of Revealing Light", cost: 3, copies: 2, type: "spell" },
        { id: "sp93", name: "Maku, The Magical Mist", cost: 3, copies: 1, type: "spell" },
        { id: "sp94", name: "Ookazi", cost: 3, copies: 1, type: "spell" },
        { id: "sp95", name: "Gift of The Martyr", cost: 3, copies: 1, type: "spell" },
        { id: "sp96", name: "The Cheerful Coffin", cost: 3, copies: 1, type: "spell" },
        { id: "sp97", name: "Nobleman of Crossout", cost: 3, copies: 1, type: "spell" },
        { id: "sp98", name: "Toon Table of Contents", cost: 3, copies: 1, type: "spell" },
        { id: "sp99", name: "Dragged Down Into The Grave", cost: 3, copies: 1, type: "spell" },
        { id: "sp100", name: "Trade-in", cost: 3, copies: 1, type: "spell" },
        { id: "sp101", name: "Card Destruction", cost: 5, copies: 1, type: "spell" },
        { id: "sp102", name: "Dragon's Mirror", cost: 5, copies: 2, type: "spell" },
        { id: "sp103", name: "Ancient Rules", cost: 5, copies: 2, type: "spell" },
		{ id: "sp999", name: "Book of Life", cost: 5, copies: 2, type: "spell" },
        { id: "sp104", name: "Meteor of Destruction", cost: 5, copies: 1, type: "spell" },
        { id: "sp105", name: "Upstart Goblin", cost: 5, copies: 2, type: "spell" },
        { id: "sp106", name: "Fusion Recovery", cost: 5, copies: 3, type: "spell" },
        { id: "sp107", name: "Reinforcement of The Army", cost: 5, copies: 2, type: "spell" },
        { id: "sp108", name: "Tribute Burial", cost: 5, copies: 1, type: "spell" },
        { id: "sp109", name: "Messenger of Peace", cost: 5, copies: 1, type: "spell" },
        { id: "sp110", name: "Chain Energy", cost: 5, copies: 1, type: "spell" },
        { id: "sp111", name: "Dark Magic Curtain", cost: 5, copies: 1, type: "spell" },
        { id: "sp112", name: "The Forceful Sentry", cost: 5, copies: 2, type: "spell" },
        { id: "sp113", name: "Mind Control", cost: 5, copies: 1, type: "spell" },
        { id: "sp114", name: "Gold Sarcophagus", cost: 5, copies: 1, type: "spell" },
        { id: "sp115", name: "Double Summon", cost: 5, copies: 1, type: "spell" },
        { id: "sp116", name: "Summoner's Art", cost: 5, copies: 1, type: "spell" },
        { id: "sp117", name: "One Day of Peace", cost: 5, copies: 1, type: "spell" },
        { id: "sp118", name: "Limiter Removal", cost: 5, copies: 2, type: "spell" },
        { id: "sp119", name: "Megamorph", cost: 5, copies: 1, type: "spell" },
        { id: "sp120", name: "Axe of Despair", cost: 5, copies: 2, type: "spell" },
        { id: "sp121", name: "Advanced Ritual Art", cost: 5, copies: 1, type: "spell" },
        { id: "sp122", name: "Ectoplasmer", cost: 5, copies: 2, type: "spell" },
        { id: "sp123", name: "Pot of Greed", cost: 10, copies: 2, type: "spell" },
        { id: "sp124", name: "United We Stand", cost: 10, copies: 1, type: "spell" },
        { id: "sp125", name: "Graceful Charity", cost: 10, copies: 2, type: "spell" },
        { id: "sp126", name: "Monster Reborn", cost: 10, copies: 2, type: "spell" },
        { id: "sp127", name: "Pre-Preparation of Rites", cost: 10, copies: 2, type: "spell" },
        { id: "sp128", name: "Zombie World", cost: 3, copies: 1, type: "spell" },
        { id: "sp129", name: "Necrovalley", cost: 10, copies: 1, type: "spell" },
        { id: "sp130", name: "Raigeki", cost: 20, copies: 2, type: "spell" },
        { id: "sp131", name: "Dark Hole", cost: 20, copies: 2, type: "spell" },
        { id: "sp132", name: "Harpie's Feather Duster", cost: 20, copies: 2, type: "spell" }
		{ id: "sp133", name: "Heavy Storm", cost: 20, copies: 1, type: "spell" }
    ],

    traps: [
        { id: "t1", name: "Numinous Healer", cost: 1, copies: 2, type: "trap" },
        { id: "t2", name: "Jam Defender", cost: 1, copies: 1, type: "trap" },
        { id: "t3", name: "Dark Factory of More Production", cost: 3, copies: 1, type: "trap" },
        { id: "t4", name: "Black Horn of Heaven", cost: 3, copies: 1, type: "trap" },
        { id: "t5", name: "Horn of Heaven", cost: 3, copies: 1, type: "trap" },
        { id: "t6", name: "Ring of Destruction", cost: 3, copies: 1, type: "trap" },
        { id: "t7", name: "Tiki Curse", cost: 3, copies: 1, type: "trap" },
        { id: "t8", name: "Tornado Wall", cost: 3, copies: 1, type: "trap" },
        { id: "t9", name: "Swamp Mirrorer", cost: 3, copies: 1, type: "trap" },
        { id: "t10", name: "Appropriate", cost: 3, copies: 1, type: "trap" },
        { id: "t11", name: "Statue of Anguish Pattern", cost: 3, copies: 1, type: "trap" },
        { id: "t12", name: "Dark Bribe", cost: 3, copies: 1, type: "trap" },
        { id: "t13", name: "Barrel Behind The Door", cost: 3, copies: 1, type: "trap" },
        { id: "t14", name: "Judgment of Anubis", cost: 3, copies: 1, type: "trap" },
        { id: "t15", name: "Card Crush Virus", cost: 3, copies: 1, type: "trap" },
        { id: "t16", name: "Magic Cylinder", cost: 3, copies: 1, type: "trap" },
        { id: "t17", name: "Reckless Greed", cost: 3, copies: 1, type: "trap" },
        { id: "t18", name: "Dark Renewal", cost: 3, copies: 1, type: "trap" },
        { id: "t19", name: "Metalmorph", cost: 3, copies: 1, type: "trap" },
        { id: "t20", name: "Torrential Tribute", cost: 3, copies: 1, type: "trap" },
        { id: "t21", name: "Bottomless Trap Hole", cost: 3, copies: 2, type: "trap" },
        { id: "t22", name: "Gryphon Wing", cost: 3, copies: 1, type: "trap" },
        { id: "t23", name: "Mask of Restrict", cost: 5, copies: 1, type: "trap" },
        { id: "t24", name: "Gravity Bind", cost: 5, copies: 1, type: "trap" },
        { id: "t25", name: "Mirror Wall", cost: 5, copies: 1, type: "trap" },
        { id: "t26", name: "Necro Fusion", cost: 5, copies: 1, type: "trap" },
        { id: "t27", name: "Call of The Haunted", cost: 5, copies: 2, type: "trap" },
        { id: "t28", name: "Dimensional Prison", cost: 5, copies: 1, type: "trap" },
        { id: "t29", name: "Mirror Force", cost: 5, copies: 2, type: "trap" },
        { id: "t30", name: "Solemn Judgment", cost: 10, copies: 2, type: "trap" }
    ]
};